name: odroidxu4-kernel
version: 4.9.38
summary: Hardkernel odroid xu4 armhf kernel
description: odroid xu4 kernel as a snap
type: kernel
architectures:
  - armhf
confinement: strict
grade: stable

parts:
  kernel:
    plugin: kernel
    source: git://github.com/JulianLiu/linux-odroid
    source-branch: odroidxu4-4.9.y
    source-type: git
    prepare: |
      git apply ../../../0009-UBUNTU-SAUCE-no-up-apparmor-rebase-of-apparmor3.5-be.patch
      git clone -b aufs4.9 https://github.com/sfjro/aufs4-standalone.git aufs4.9
      git apply aufs4.9/aufs4-kbuild.patch
      git apply aufs4.9/aufs4-base.patch
      git apply aufs4.9/aufs4-mmap.patch
      git apply aufs4.9/aufs4-standalone.patch
      cp -Rp aufs4.9/Documentation/* Documentation/
      cp -Rp aufs4.9/fs/* fs/
      cp aufs4.9/include/uapi/linux/aufs_type.h include/uapi/linux/
    kdefconfig: [odroidxu4_defconfig, snappy/generic.config, snappy/security.config, snappy/systemd.config, snappy/snappy.config, snappy/containers.config]
    kernel-initrd-modules:
      - squashfs
    kernel-image-target: zImage
    kernel-device-trees:
      - exynos5422-odroidxu4
    build-packages: [bc, lzop, cpio, kmod]
  firmware:
    plugin: nil
    source: .
    install: |
      mkdir -p $SNAPCRAFT_PART_INSTALL/firmware
      tar xf firmware.tar -C $SNAPCRAFT_PART_INSTALL/firmware
    after:
      - kernel
